[build]
target = "riscv32imac-unknown-none-elf"

[alias]
run-demo = "run --release --example"

[target.riscv32imac-unknown-none-elf]
# runner = "wchisp flash"
# runner = "wlink -v flash --no-erase --dry-run"
runner = "wlink -v flash --no-erase"
rustflags = [
    # "-C", "link-arg=-Tmemory.x",
    "-C",
    "link-arg=-Tlink.x",
    # "--emit", "obj",
    # "--emit", "asm",
]
